/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAccordion: typeof import('bootstrap-vue-next/components/BAccordion')['BAccordion']
    BAccordionItem: typeof import('bootstrap-vue-next/components/BAccordion')['BAccordionItem']
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BCardTitle: typeof import('bootstrap-vue-next/components/BCard')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BImg: typeof import('bootstrap-vue-next/components/BImg')['BImg']
    BLink: typeof import('bootstrap-vue-next/components/BLink')['BLink']
    BOffcanvas: typeof import('bootstrap-vue-next/components/BOffcanvas')['BOffcanvas']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
  }
  export interface ComponentCustomProperties {
    vBToggle: typeof import('bootstrap-vue-next/directives/BToggle')['vBToggle']
  }
}
